version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres-user
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=supersecretpassword
